name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        env:
          #these are github secrets
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          # Save the SSH private key and set the permissions
          echo "$SSH_PRIVATE_KEY" > MY_KEY.pem
          chmod 600 MY_KEY.pem


      - name: Deploy to EC2
        run: |
          # Define EC2 instance details
          INSTANCE_ID="i-092f34c9f20ed71ae"
          PUBLIC_IP=3.91.168.107

          # SSH into EC2 and deploy
          ssh -vvv -o StrictHostKeyChecking=no -i MY_KEY.pem ubuntu@$PUBLIC_IP << 'EOF'
          set -e

          # Update system and install dependencies
          sudo apt-get update -y
          sudo apt-get install -y ruby-full build-essential zlib1g-dev libyaml-dev libssl-dev libreadline-dev libncurses5-dev libffi-dev libsqlite3-dev

          # Install Node.js and Yarn
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g yarn

          # Navigate to the home directory
          cd /home/ubuntu

          # Clone the repository if it doesn't exist
          if [ ! -d "CAD_CA1" ]; then
            git clone https://github.com/janekeyes/CAD-CA1.git
          fi

          cd CAD_CA1
          git pull origin master

          # Install Ruby dependencies
          bundle install

          # Run database migrations
          rake db:migrate

          echo "Deployment Complete"


          EOF

        #change has been made again

