name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Jane Keyes"
          git config --global user.email "janekeyes123@gmail.com"

      - name: Set up Environment Variables
        env:
          #these are github secrets
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          #save the ssh private key and set the permissions
          echo "$SSH_PRIVATE_KEY" > MY_KEY.pem
          chmod 600 MY_KEY.pem
          ls -l MY_KEY.pem
          

      - name: Deploy to EC2
        run: |
          #define ec2 instance details
          INSTANCE_ID="i-092f34c9f20ed71ae"
          PUBLIC_IP="3.91.168.107"

          ssh -vvv -o StrictHostKeyChecking=no -i MY_KEY.pem ubuntu@$PUBLIC_IP << 'EOF'
            #exit if errors occur
            set -e

            #update system
            sudo apt-get update -y

            #navigate to the directory
            cd /home/ubuntu

            #pull latest changes from GitHub
            if [ ! -d "CAD_CA1" ]; then
              git clone https://github.com/janekeyes/CAD-CA1.git
            fi

            cd CAD_CA

            #pull latest changes
            git pull origin main

            #install ruby rails dependencies
            bundle install
            rake db:migrate
            #presompile assets if necessary
            #rake assets:precompile

          echo "Deployment Complete"
          EOF

        #change has been made
