name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up SSH agent
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 3. Deploy the code to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.91.168.10 << 'EOF'
        set -e
        cd ~/clothing_app || git clone https://github.com/janekeyes/ClothingApp.git clothing_app && cd clothing_app
        git pull origin main
        bundle install
        yarn install
        RAILS_ENV=production bundle exec rake assets:precompile
        RAILS_ENV=production bundle exec rake db:migrate
        sudo systemctl restart puma
        EOF
